HOST: http://www.google.com/

--- openkartslalom ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Persons
The following is a section of resources related to the shopping cart
--

List products added into your shopping-cart. (comment block again in Markdown)
GET /api/drivers
< 200
< Content-Type: application/json
{
    "csv-370": {
        "id": "Z00001",
        "class": "E",
        "lastname": "Haseitl",
        "firstname": "Johannes",
        "rookie": "",
        "zip": "30161",
        "city": "Hannover",
        "club": "MSC Altenstadt",
        "birthday": "01.02.1984",
        "oldLicence": "1045"
    }
}


GET /api/driver/:name
< 200
< Content-Type: application/json
{
    "id": "Z00001",
    "class": "E",
    "lastname": "Haseitl",
    "firstname": "Johannes",
    "rookie": "",
    "zip": "30161",
    "city": "Hannover",
    "club": "MSC Altenstadt",
    "birthday": "01.02.1984",
    "oldLicence": "1045"
}

PUT /api/driver/:name
> Accept: application/json
{
    "id": "Z00001",
    "class": "E",
    "lastname": "Haseitl",
    "firstname": "Johannes",
    "rookie": "",
    "zip": "30161",
    "city": "Hannover",
    "club": "MSC Lechbruck",
    "birthday": "01.02.1984",
    "oldLicence": "1045"
}
< 200
< Content-Type: application/json
{
    "status": "updated"
}


DELETE /api/driver/:name
> Accept: application/json
< 200
< Content-Type: application/json
{
    "status": "deleted"
}